spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: false
      types:
        print:
          banner: false
  profiles:
    active: local